version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "stein_db"
    volumes:
      - ./tmp/db:/var/lib/postgresql/db
  web:
    build: .
    entrypoint: ["./app/lib/docker-entrypoint.sh"]
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Stein
    ports:
      - "3000:3000"
    depends_on:
      - db